flo/views/notice_comment_view.py
#### 관리자 공지 게시판 댓글 컨트롤러

from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from flo import db
from flo.form import NoticeCommentForm
from flo.models.notice_model import Notice, NoticeComment
from flo.views.auth_view import login_required


bp = Blueprint('noticecomment', __name__, url_prefix='/noticecomment')


# 공지 댓글 작성
@bp.route('/write/<int:notice_idx>', methods=('POST',))
@login_required                                         # 로그인 검증
def write(notice_idx):
    try:
        form = NoticeCommentForm()
        notice = Notice.query.get(notice_idx)

        if form.validate_on_submit():
            content = request.form['content']
            noticecomment = NoticeComment(content=form.content.data, write_t=datetime.now(), user=g.user)

            notice.comment_set.append(noticecomment)
            db.session.commit()

            return redirect(url_for('notice.detail', notice_idx=notice_idx))

        if notice is None:
            raise ValueError("게시글을 찾을 수 없습니다")

        return render_template('notice/notice_detail.html', notice=notice, form=form)

    except ValueError as e:
        return board_error(e)


# 공지 댓글 삭제
@bp.route('/delete/<int:noticecomment_idx>')
@login_required
def delete(noticecomment_idx):
    try:
            noticecomment = NoticeComment.query.get(noticecomment_idx)
            notice_idx = noticecomment.notice.idx

            # 댓글은 직접 작성한 사용자만 삭제 가능
            if g.user != noticecomment.user:
                flash('삭제권한이 없습니다')
            else:
                db.session.delete(noticecomment)
                db.session.commit()

            return redirect(url_for('notice.detail', notice_idx=notice_idx))

    except ValueError as e:
            return board_error(e)


@bp.errorhandler(ValueError)
def board_error(e):
    return render_template('errors/404.html'), 404

flo/views/notice_view.py
#### 관리자 공지 게시판 컨트롤러

from flask import Blueprint, render_template, request, url_for, redirect, send_file, g, flash
from datetime import datetime
from werkzeug.utils import redirect
import os

from .. import db
from flo.models.notice_model import Notice
from flo.form import NoticeCreateForm, NoticeCommentForm
from flo.views.auth_view import login_required


# 파일 업로드
UPLOAD_FOLDER = os.path.join(os.getcwd(), '') # 경로
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])                   # 허용 가능한 확장자

# 확장자 검증
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


# 블루프린트
bp = Blueprint('notice', __name__, url_prefix='/notice')


# 공지 목록
@bp.route('/list/',  methods=('GET', 'POST'))
def notice_li():
    try:
        page = request.args.get('page', type=int, default=1)
        notice_list = Notice.query.order_by(Notice.write_t.desc())

        # 검색 기능
        search_option = request.args.get('search_option', default='all')
        search_keyword = request.args.get('search_keyword', type=str, default='')
        search_query = '%%{}%%'.format(search_keyword)

        # 검색 여부
        if search_keyword:
            if search_option == 'title':
                notice_list = notice_list.join(Notice.user).filter(
                    Notice.title.ilike(search_query)
                ).distinct()  # 중복 제거
            elif search_option == 'content':
                notice_list = notice_list.join(Notice.user).filter(
                    Notice.content.ilike(search_query)
                ).distinct()
            else:  # 전체 검색
                notice_list = notice_list.join(Notice.user).filter(
                    (Notice.title.ilike(search_query)) | (Notice.content.ilike(search_query))
                ).distinct()

        notice_list = notice_list.paginate(page=page, per_page=10)

        return render_template('notice/notice_list.html', notice_list=notice_list)

    except ValueError as e:
        return board_error(e)


# 관리자의 공지 작성하기
@bp.route('/write/', methods=('GET', 'POST'))
@login_required                                         # 로그인 검증
def write():
    form = NoticeCreateForm()

    if request.method == 'POST' and form.validate_on_submit():

        # 제목과 내용 필수 입력
        if not form.title.data or not form.content.data:
            flash("제목과 내용을 입력해주세요")

        file = request.files['fileupload']
        filename = ''
        file_path = ''

        if file and allowed_file(file.filename):
            filename = file.filename
            file_path = os.path.join(UPLOAD_FOLDER, filename)
            file.save(file_path)  # 파일 저장

        # 관리자가 아니면 등록 되지 않음
        if g.user.id == '관리자':
            notice = Notice(
                title=form.title.data,
                content=form.content.data,
                user=g.user,
                write_t=datetime.now(),
                filename=filename,
                file_path=file_path
            )

            db.session.add(notice)
            db.session.commit()

            return redirect(url_for('notice.notice_li'))

        else:
            flash('권한이 없습니다.')

    return render_template('notice/notice_write.html', form=form)


# 공지글 조회
@bp.route('/detail/<int:notice_idx>/', methods=('GET', 'POST'))
def detail(notice_idx):
    try:
        form = NoticeCommentForm()
        notice = Notice.query.get(notice_idx)

        # 게시글 없을 때
        if notice is None:
            raise ValueError

        return render_template('notice/notice_detail.html', notice=notice, form=form)

    except ValueError as e:
        return board_error(e)


# 첨부파일 다운로드
@bp.route('/download/<path:filename>',  methods=('POST',))
def download(filename):
    file_path = os.path.join(UPLOAD_FOLDER, filename)
    return send_file(file_path, filename, as_attachment=True)


# 공지 수정
@bp.route('/update/<int:notice_idx>', methods=('GET', 'POST'))
@login_required
def update(notice_idx):
    try:
        # 게시글 가져오기
        notice = Notice.query.get(notice_idx)

        # 작성한 사용자만 수정 가능함
        if g.user != notice.user:
            flash('수정권한이 없습니다')

            return redirect(url_for('notice.detail', notice_idx=notice_idx))

        if request.method == 'POST':
            form = NoticeCreateForm(request.form)  # 기존 글 가져오기

            if form.validate_on_submit():
                form.populate_obj(notice)
                notice.write_t = datetime.now()

                db.session.commit()

                flash('게시글이 성공적으로 수정되었습니다.')

                return redirect(url_for('notice.detail', notice_idx=notice_idx))
        else:
            form = NoticeCreateForm(obj=notice)     # 데이터 전달

        return render_template('notice/notice_write.html', form=form)

    except Exception as e:
        return board_error(e)


# 공지 삭제
@bp.route('/delete/<int:notice_idx>')
@login_required
def delete(notice_idx):
    try:
        notice = Notice.query.get(notice_idx)

        # 사용자 확인
        if g.user != notice.user or not g.user.id == '관리자':
            flash('권한이 없습니다')
            return redirect(url_for('notice.detail', notice_idx=notice_idx))

        db.session.delete(notice)
        db.session.commit()

        return redirect(url_for('notice.notice_li'))

    except ValueError as e:
        return board_error(e)


# 공지 좋아요
@bp.route('/like/<int:notice_idx>/')
@login_required
def like(notice_idx):
    notice = Notice.query.get(notice_idx)

    if g.user == notice.user:
        flash('본인이 작성한 글은 공감할 수 없습니다')
    else:
        if g.user in notice.like:
            flash('이미 공감 했습니다')
        else:
            notice.like.append(g.user)
            db.session.commit()

    return redirect(url_for('notice.detail', notice_idx=notice_idx))


# 오류 핸들러
@bp.errorhandler(ValueError)
def board_error(e):
    return render_template('errors/404.html')

flo/templates/notice/notice_detail.html
<!-- 공지 조회 -->

{% extends 'base.html' %}
{% block content %}
{% include "errors/form_errors.html" %}

<div class="container my-3">

    <!-- 에러 -->
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}

  <!-- 게시글 -->
  <h3 class="border-bottom py-2">{{ notice.title }}</h3>
  <div class="card my-3">
    <div class="card-body">

        <!-- 작성 내용 -->
      <div class="card-text" style="white-space:pre-line;">
          {{ notice.content }}
      </div>

        <!-- 작성 정보 -->
      <div class="d-flex justify-content-end">

          <!-- 수정 날짜 -->
          {% if notice.update_t %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">modified at</div>
                <div>{{ notice.update_t|datetime }}</div>
            </div>
          {% endif %}

          <div class="badge bg-light text-dark p-2">

              <!-- 작성자 -->
              <div class="mb-2">
                  {{ notice.user.member_name }}
              </div>

              <!-- 작성 날짜 -->
              <div class="mb-2">
                  {{ notice.write_t }}
              </div>

          </div>
      </div>


        <div class="my-3">

            <!-- 좋아요 -->
            <a href="javascript:void(0)" data-uri="{{ url_for('notice.like', notice_idx=notice.idx) }}"
               class="recommend btn btn-sm btn-outline-secondary"> 좋아요
                <span class="badge rounded-pill bg-success">{{ notice.like|length }}</span>
            </a>

            <!-- 사용자 검증 -->
            {% if g.user == notice.user or g.user.id == '관리자'%}

            <!-- 수정 -->
            <a href="{{ url_for('notice.update', notice_idx=notice.idx) }}"
               class="btn btn-sm btn-outline-secondary">수정</a>

            <!-- 삭제 -->
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{{ url_for('notice.delete', notice_idx=notice.idx) }}">삭제</a>

            {% endif %}
        </div>


        <!-- 파일 다운로드 -->
        {% if notice.file_path %}
        <div class="mb-3">
            <h5 class="border-bottom py-2">첨부 파일</h5>
            <form action="/notice/download/{{ notice.file_path }}" method="POST" enctype = "multipart/form-data">
                <button type="submit" class="btn btn-primary">다운로드</button>
            </form>
        </div>
        {% endif %}
    </div>
  </div>



  <!-- 댓글 -->
  <h5 class="border-bottom my-3 py-2">{{ notice.comment_set|length }} 개의 답변이 있습니다.</h5>
  {% for noticecomment in notice.comment_set %}
  <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space:pre-line;">{{ noticecomment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    <!-- 작성자 -->
                  <div class="mb-2">
                      {{ g.user.member_name }}
                  </div>
                  <!-- 작성 날짜 -->
                  <div class="mb-2">
                      {{ notice.write_t }}
                  </div>
                </div>
            </div>

            <!-- 댓글 삭제 -->
            <div class="my-3">
                {% if g.user == noticecomment.user %}
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{{ url_for('noticecomment.delete', noticecomment_idx=noticecomment.idx) }}">삭제</a>
                {% endif %}
            </div>

        </div>
    </div>
    {% endfor %}

    <!-- 댓글 등록 -->
    <form action="{{ url_for('noticecomment.write', notice_idx=notice.idx) }}" method="post" class="my-3">

        <!-- CSRF 토큰 처리 -->
        {{ form.csrf_token }}

        <!-- 에러 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}

        <div class="mb-3">
            <label for="content">댓글 내용</label>
            <textarea name="content" id="content" class="form-control" rows="5"></textarea>
        </div>

        {% if not g.user %}
<!--            <button class="btn btn-primary" type="submit" id="button-addon2">등록</button>-->
        {% else %}
            <button class="btn btn-primary" type="submit" id="button-addon2">등록</button>
        {% endif %}
    </form>

</div>
{% endblock %}


<!-- script  -->
{% block script %}

<script type='text/javascript'>

    <!-- 댓글 삭제 -->
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    <!-- 게시글 좋아요 -->
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("공감하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}

flo/templates/notice/notice_list.html
<!-- 공지 목록 -->

{% extends 'base.html' %}
{% block content %}


<div id="flash-messages">
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class="flash-messages">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
</div>

<!-- 검색 기능  -->
<div class="col-6 board-container">
    <div class="row my-3">
        <div class="col-6">
            <h3> 공지사항 </h3>
        </div>

        <form method="get" action="{{ url_for('notice.notice_li') }}">s
            <select class="form-select" id="exampleSelect1" name="search_option">
                <option value="all"> {% if search_option == 'all' %}전체{% endif %}전체</option>
                <option value="title"> {% if search_option == 'title' %}제목{% endif %}제목</option>
                <option value="content"> {% if search_option == 'content' %}내용{% endif %}내용</option>
            </select>
            <input type="text"  class="form-control me-sm-2"  name="search_keyword" value="{{ search_keyword }}" placeholder="keyword">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">검색</button>
        </form>

        {% if search_keyword %}
            <p>검색어: {{ search_keyword }}</p>
            <p>검색 옵션: {{ search_option }}</p>
        {% endif %}

        {{ notice_list.links }}
    </div>
</div>


<!-- 게시글 목록 -->
<div class = "container my-3">
    <table class="table table-hover">
        <thead>
        <tr class="table-primary">
            <th scope="row">No</th>
                <td>제목</td>
                <td>작성자</td>
                <td>작성일</td>
            </tr>
        </thead>

        <tbody>
            {% if notice_list %}
            {% for notice in notice_list.items %}
            <tr>
                <!-- 게시글 번호 -->
                <td>{{ notice_list.total - ((notice_list.page-1) * notice_list.per_page) - loop.index0 }}</td>
                <td>

                    <!-- 제목 -->
                  <a href="{{ url_for('notice.detail', notice_idx=notice.idx) }}">{{ notice.title }}</a>

                    <!-- 답변 개수 -->
                    {% if notice.comment_set|length > 0 %}
                    <span class="text-danger small mx-2">{{ notice.comment_set|length }}</span>
                    {% endif %}
                </td>

                <!-- 작성자 -->
                <td>{{ notice.user.member_name }}</td>

                <!-- 작성일 -->
                <td>
                    {{ notice.write_t }}
                </td>

            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3"> 게시글이 존재하지 않습니다. </td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    <!-- 페이징 -->
    <ul class="pagination justify-content-center">

        <!-- 이전페이지 -->
        {% if notice_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ notice_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in notice_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != notice_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if notice_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ notice_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>

    <!-- 작성 버튼 -->
    {% if g.user.id == '관리자' %}
        <a href="{{ url_for('notice.write') }}" class="btn btn-primary">게시글 작성</a>
    {% endif %}
</div>

{% endblock %}


<!-- 검색 및 페이징 처리 스크립트 -->
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('search_keyword').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

flo/templates/notice/notice_write.html
<!-- 공지 작성하기 -->

{% extends 'base.html' %}
{% block content %}

<!-- 본문  -->
<div class="container">
    <h3 class="my-3 border-bottom py-2">공지 작성</h3>
    <form  method="post" class="my-3" enctype="multipart/form-data">

        <!-- CSRF 토큰 처리 -->
        {{ form.csrf_token }}

        <!-- 에러 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}


        <!-- 게시글 작성 -->
        <div class="mb-3">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ form.title.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>

        <!-- 파일 업로드 -->
        <div class="form-group">
            <label for="fileupload">파일 업로드</label>
            <input type="file" class="form-control" name="fileupload" id="fileupload">
        </div>

        {% if g.user.id == '관리자' %}
            <button class="btn btn-primary" type="submit" id="button-addon2">등록</button>
        {% endif %}
    </form>
</div>

{% endblock %}