flo/views/board_view.py
#### 일반 사용자 게시판

from flask import Blueprint, render_template, request, url_for, redirect, send_file,g, flash
from datetime import datetime
from werkzeug.utils import redirect
from sqlalchemy.exc import SQLAlchemyError
import os

from .. import db
from flo.models.board_model import Board
from flo.form import BoardCreateForm, CommentForm
from flo.views.auth_view import login_required


# 파일 업로드
UPLOAD_FOLDER = os.path.join(os.getcwd(), '') # 경로
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])                   # 허용 가능한 확장자

# 확장자 검증
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


# 블루프린트
bp = Blueprint('board', __name__, url_prefix='/board')


# 게시글 목록
@bp.route('/list/', methods=('GET', 'POST'))
def board_li():
    try:
        page = request.args.get('page', type=int, default=1)
        board_list = Board.query.order_by(Board.write_t.desc())

        # 검색 기능
        search_option = request.args.get('search_option', default='all')
        search_keyword = request.args.get('search_keyword', type=str, default='')
        search_query = '%%{}%%'.format(search_keyword)

        # 검색 여부
        if search_keyword:
            if search_option == 'title':
                board_list = board_list.join(Board.user).filter(
                    Board.title.ilike(search_query)
                ).distinct()  # 중복 제거
            elif search_option == 'content':
                board_list = board_list.join(Board.user).filter(
                    Board.content.ilike(search_query)
                ).distinct()
            else:  # 전체 검색
                board_list = board_list.join(Board.user).filter(
                    (Board.title.ilike(search_query)) | (Board.content.ilike(search_query))
                ).distinct()

        board_list = board_list.paginate(page=page, per_page=10)

        return render_template('board/board_list.html', board_list=board_list)

    except ValueError as e:
        return board_error(e)


# 게시글 작성하기
@bp.route('/write/', methods=('GET', 'POST'))
@login_required                                         # 로그인 검증
def write():
    try:
        form = BoardCreateForm()
        posting_password = request.form.get('posting_password')

        if request.method == 'POST' and form.validate_on_submit():
            if form.validate_on_submit():

                # 제목과 내용 필수 입력
                if not form.title.data or not form.content.data:
                    flash( "제목과 내용을 입력해주세요")
                elif len(form.posting_password.data) > 8:
                    flash("게시글 비밀번호는 8자리 이하로 설정해주세요")

                # 파일은 업로드 하지 않을 경우 빈 문자열로 저장
                else:
                    file = request.files['fileupload']
                    filename = ''
                    file_path = ''

                    if file and allowed_file(file.filename):
                        filename = file.filename
                        file_path = os.path.join(UPLOAD_FOLDER, filename)
                        file.save(file_path)  # 파일 저장

                    posting_password = form.posting_password.data
                    if not posting_password:
                        posting_password = None

                    board = Board(
                        title=form.title.data,
                        content=form.content.data,
                        write_t=datetime.now(),
                        filename=filename,
                        file_path=file_path,
                        user=g.user,
                        posting_password=form.posting_password.data)
                    db.session.add(board)
                    db.session.commit()

                    return redirect(url_for('board.board_li'))

            else:
                flash('입력 양식을 확인해주세요')
                return render_template('board/board_write.html', form=form)



        return render_template('board/board_write.html', form=form)

    except SQLAlchemyError as e:
        board_error(e)



# 비밀글
@bp.route('/secret/<int:board_idx>/', methods=('POST', 'GET'))
def secret(board_idx):
    try:
        form = BoardCreateForm()
        board = Board.query.get(board_idx)

        # 게시글 조회
        if board.posting_password == 'NULL' or g.user.id == '관리자':
            return render_template('board/board_detail.html', board=board, form=form)

        # 비밀번호 검증
        if request.method == 'POST' and form.validate_on_submit():
                if board.posting_password == form.posting_password.data:
                    return render_template('board/board_detail.html', board=board, form=form)

        return render_template('board/board_password.html', board=board, form=form)

    except ValueError as e:
        return board_error(e)

    except AttributeError as e:
        flash('권한이 없습니다')
        return redirect(url_for('board.board_li'))


# 게시글 조회
@bp.route('/detail/<int:board_idx>/', methods=('GET', 'POST'))
def detail(board_idx):
    try:
        pass_form = BoardCreateForm()
        form = CommentForm()
        board = Board.query.get(board_idx)

        # 게시글 없을 때
        if board is None:
            raise ValueError

        return render_template('board/board_detail.html', board=board, form=form)

    except ValueError as e:
        return board_error(e)


# 첨부파일 다운로드
@bp.route('/download/<path:filename>',  methods=('POST',))
def download(filename):
    file_path = os.path.join(UPLOAD_FOLDER, filename)
    return send_file(file_path, filename, as_attachment=True)


# 게시글 수정
@bp.route('/update/<int:board_idx>', methods=('GET', 'POST'))
@login_required
def update(board_idx):
    try:
        # 게시글 가져오기
        board = Board.query.get(board_idx)

        # 작성한 사용자만 수정 가능함
        if g.user != board.user:
            flash('수정권한이 없습니다')

            return redirect(url_for('board.detail', board_idx=board_idx))

        if request.method == 'POST':
            form = BoardCreateForm(request.form)  # 기존 글 가져오기

            if form.validate_on_submit():
                form.populate_obj(board)
                board.write_t = datetime.now()

                db.session.commit()

                flash('게시글이 성공적으로 수정되었습니다.')

                return redirect(url_for('board.detail', board_idx=board_idx))
        else:
            form = BoardCreateForm(obj=board)

        return render_template('board/board_write.html', form=form)

    except Exception as e:
        return board_error(e)

# 게시글 삭제
@bp.route('/delete/<int:board_idx>')
@login_required
def delete(board_idx):
    try:
        board = Board.query.get(board_idx)

        # 작성한 사용자 또는 관리자만 삭제 가능
        if g.user != board.user and not g.user.id == 'iamadmin':
            flash('권한이 없습니다')
            return redirect(url_for('board.detail', board_idx=board_idx))

        db.session.delete(board)
        db.session.commit()

        return redirect(url_for('board.board_li'))

    except ValueError as e:
        return board_error(e)


# 게시글 좋아요
@bp.route('/like/<int:board_idx>/')
@login_required
def like(board_idx):
    board = Board.query.get(board_idx)

    if g.user == board.user:
        flash('본인이 작성한 글은 공감할 수 없습니다')
    else:
        if g.user in board.like:
            flash('이미 공감 했습니다')
        else:
            board.like.append(g.user)
            db.session.commit()

    return redirect(url_for('board.detail', board_idx=board_idx))


# 오류 핸들러
@bp.errorhandler(ValueError)
def board_error(e):
    return render_template('errors/404.html')

flo/views/comment_view.py
#### 일반 게시글의 댓글 컨트롤러

from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from flo import db
from flo.form import CommentForm
from flo.models.board_model import Board, Comment
from flo.views.auth_view import login_required


bp = Blueprint('comment', __name__, url_prefix='/comment')


# 댓글 작성하기
@bp.route('/write/<int:board_idx>', methods=('POST',))
@login_required                                         # 로그인 검증
def write(board_idx):
    try:
        form = CommentForm()
        board = Board.query.get(board_idx)
        content = request.form['content']

        # 댓글 낸용, 작성 시간, 작성자 정보
        if form.validate_on_submit():
            content = request.form['content']
            comment = Comment(content=content, write_t=datetime.now(), user=g.user)

            board.comment_set.append(comment)
            db.session.commit()

            return redirect(url_for('board.detail', board_idx=board_idx))

        if board is None:
            raise ValueError("게시글을 찾을 수 없습니다")

        return render_template('board/board_detail.html', board=board, form=form)

    except ValueError as e:
        return board_error(e)


# 댓굴 삭제
@bp.route('/delete/<int:comment_idx>')
@login_required
def delete(comment_idx):
    try:
        comment = Comment.query.get(comment_idx)
        board_idx = comment.board.idx

        # 댓글은 작성자만 삭제 가능
        if g.user != comment.user:
            flash('삭제권한이 없습니다')
        else:
            db.session.delete(comment)
            db.session.commit()

        return redirect(url_for('board.detail', board_idx=board_idx))

    except ValueError as e:
        return board_error(e)


@bp.errorhandler(ValueError)
def board_error(e):
    return render_template('errors/404.html'), 404

flo/templates/board/board_detail.html
<!-- 게시글 조회 -->

{% extends 'base.html' %}
{% block content %}

<div class="container my-3">

    <!-- 에러 -->
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}

  <!-- 게시글 -->
  <h3 class="border-bottom py-2">{{ board.title }}</h3>
  <div class="card my-3">
    <div class="card-body">

        <!-- 작성 내용 -->
      <div class="card-text" style="white-space:pre-line;">
          {{ board.content }}
      </div>

        <!-- 작성 정보 -->
      <div class="d-flex justify-content-end">

          <!-- 수정 날짜 -->
          {% if board.write_t %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">modified at</div>
                <div>{{ board.write_t }}</div>
            </div>
          {% endif %}

          <div class="badge bg-light text-dark p-2">

              <!-- 작성자 -->
              <div class="mb-2">
                  {{ board.user.member_name }}
              </div>

              <!-- 작성 날짜 -->
              <div class="mb-2">
                  {{ board.write_t }}
              </div>

          </div>
      </div>



        <div class="my-3">

            <!-- 좋아요 -->
            <a href="javascript:void(0)" data-uri="{{ url_for('board.like', board_idx=board.idx) }}"
               class="recommend btn btn-sm btn-outline-secondary"> 좋아요
                <span class="badge rounded-pill bg-success">{{ board.like|length }}</span>
            </a>

            <!-- 사용자 검증 -->
            {% if g.user == board.user or g.user.id == '관리자'%}

            <!-- 수정 -->
            <a href="{{ url_for('board.update', board_idx=board.idx) }}"
               class="btn btn-sm btn-outline-secondary">수정</a>

            <!-- 삭제 -->
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{{ url_for('board.delete', board_idx=board.idx) }}">삭제</a>

            {% endif %}
        </div>


        <!-- 파일 다운로드 -->
        {% if board.file_path %}
        <div class="mb-3">
            <h5 class="border-bottom py-2">첨부 파일</h5>
            <form action="/board/download/{{ board.file_path }}" method="POST" enctype = "multipart/form-data">
                <button type="submit" class="btn btn-primary">다운로드</button>
            </form>
        </div>
        {% endif %}
    </div>
  </div>



  <!-- 댓글 -->
  <h5 class="border-bottom my-3 py-2">{{ board.comment_set|length }} 개의 답변이 있습니다.</h5>
  {% for comment in board.comment_set %}
  <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space:pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    <!-- 작성자 -->
                      <div class="mb-2">
                          {{ g.user.member_name }}
                      </div>
                      <!-- 작성 날짜 -->
                      <div class="mb-2">
                          {{ board.write_t }}
                      </div>
                </div>
            </div>

            <!-- 댓글 삭제 -->
            <div class="my-3">
                {% if g.user == comment.user or g.user.id == '관리자' %}
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{{ url_for('comment.delete', comment_idx=comment.idx) }}">삭제</a>
                {% endif %}
            </div>


        </div>
    </div>
    {% endfor %}

    <!-- 댓글 등록 -->
    <form action="{{ url_for('comment.write', board_idx=board.idx) }}" method="post" class="my-3">

        <!-- CSRF 토큰 처리 -->
        {{ form.csrf_token }}

        <!-- 에러 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}

        <div class="mb-3">
            <label for="content">댓글 내용</label>
            <textarea name="content" id="content" class="form-control" rows="5"></textarea>
        </div>

        {% if not g.user %}
<!--            <button class="btn btn-primary" type="submit" id="button-addon2">등록</button>-->
        {% else %}
            <button class="btn btn-primary" type="submit" id="button-addon2">등록</button>
        {% endif %}

    </form>

</div>
{% endblock %}


<!-- script  -->
{% block script %}

<script type='text/javascript'>

    <!-- 댓글 삭제 -->
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    <!-- 게시글 좋아요 -->
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("공감하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

</script>
{% endblock %}

flo/templates/board/board_list.html
<!-- 게시글 목록 -->

{% extends 'base.html' %}
{% block content %}

<div id="flash-messages">
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class="flash-messages">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
</div>

<!-- 검색 기능  -->
<div class="col-6 board-container">
    <div class="row my-3">
        <div class="col-6">
            <h3> 일반 게시판 </h3>
        </div>

        <form method="get" action="{{ url_for('board.board_li') }}">
            <select class="form-select" id="exampleSelect1" name="search_option">
                <option value="all"> {% if search_option == 'all' %}전체{% endif %}전체</option>
                <option value="title"> {% if search_option == 'title' %}제목{% endif %}제목</option>
                <option value="content"> {% if search_option == 'content' %}내용{% endif %}내용</option>
            </select>
            <input type="text"  class="form-control me-sm-2"  name="search_keyword" value="{{ search_keyword }}" placeholder="keyword">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">검색</button>
        </form>

        {% if search_keyword %}
            <p>검색어: {{ search_keyword }}</p>
            <p>검색 옵션: {{ search_option }}</p>
        {% endif %}

<!--        <ul>-->
<!--            {% for board in board_list.items %}-->
<!--                <li>{{ board.title }}</li>-->
<!--            {% endfor %}-->
<!--        </ul>-->

        {{ board_list.links }}
    </div>
</div>


<!-- 게시글 목록 -->
<div class = "container my-3">
    <table class="table table-hover">
        <thead>
        <tr class="table-primary">
            <th scope="row">No</th>
                <td>제목</td>
                <td>비밀글 여부</td>
                <td>작성자</td>
                <td>작성일</td>
            </tr>
        </thead>

        <tbody>
            {% if board_list %}
            {% for board in board_list.items %}
            <tr>
                <!-- 게시글 번호 -->
                <td>{{ board_list.total - ((board_list.page-1) * board_list.per_page) - loop.index0 }}</td>
                <td>
<!--                    <a href="{{ url_for('board.detail', board_idx=board.idx) }}">{{ board.title }}</a>-->

                    <!-- 비밀글 따라 달라짐 -->
                    {% if board.posting_password is none %}
                        <a href="{{ url_for('board.detail', board_idx=board.idx) }}">{{ board.title }}</a>
                    {% elif board.posting_password == '' %}
                         <a href="{{ url_for('board.detail', board_idx=board.idx) }}">{{ board.title }}</a>
                    {% else %}
                        <a href="{{ url_for('board.secret', board_idx=board.idx) }}">{{ board.title }}</a>
                    {% endif %}

                    <!-- 답변 개수 -->
                    {% if board.comment_set|length > 0 %}
                    <span class="text-danger small mx-2">{{ board.comment_set|length }}</span>
                    {% endif %}
                </td>

                <!-- 비밀글 여부 -->
                <td>
                    {% if board.posting_password is none %}
                        <span class="text-success">공개</span>
                    {% elif board.posting_password == '' %}
                        <span class="text-success">공개</span>
                    {% else %}
                        <span class="text-danger">비밀글</span>
                    {% endif %}
                </td>

                <!-- 작성자 -->
                <td>{{ board.user.member_name }}</td>

                <!-- 작성일 -->
                <td>
                    {{ board.write_t }}
                </td>


            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3"> 게시글이 존재하지 않습니다. </td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    <!-- 페이징 -->
    <ul class="pagination justify-content-center">

    <!-- 이전페이지 -->
    {% if board_list.has_prev %}
    <li class="page-item">
        <a class="page-link" data-page="{{ board_list.prev_num }}" href="javascript:void(0)">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
    </li>
    {% endif %}
    {% for page_num in board_list.iter_pages() %}
    {% if page_num %}
    {% if page_num != board_list.page %}
    <li class="page-item">
        <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
    </li>
    {% else %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="#">{{ page_num }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled">
        <a class="page-link" href="javascript:void(0)">...</a>
    </li>
    {% endif %}
    {% endfor %}

    <!-- 다음페이지 -->
    {% if board_list.has_next %}
    <li class="page-item">
        <a class="page-link" data-page="{{ board_list.next_num }}" href="javascript:void(0)">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <button class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</button>
<!--        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>-->
    </li>
    {% endif %}
</ul>

    <!-- 작성 버튼 -->
    {% if not g.user %}
        <a href="{{ url_for('board.write') }}" class="btn btn-primary">게시글 작성</a>
    {% else %}
        <a href="{{ url_for('board.write') }}" class="btn btn-primary">게시글 작성</a>
    {% endif %}

</div>

<!-- 검색 폼 -->
<!--<form id="searchForm" method="get" action="{{ url_for('board.board_li') }}">-->
<!--    <input type="hidden" id="search_keyword" name="search_keyword" value="{{ search_keyword or '' }}">-->
<!--    <input type="hidden" id="page" name="page" value="{{ page }}">-->
<!--</form>-->

{% endblock %}


<!-- 검색 및 페이징 처리 스크립트 -->
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('search_keyword').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

flo/templates/board/board_password.html
<!-- 비밀글 비밀번호 -->

{% extends 'base.html' %}
{% block content %}


<div class="container">
    <h3 class="my-3 border-bottom py-2">비밀번호 확인</h3>

    <form method="post" class="post-form my-3">
        <!-- CSRF 토큰 처리 -->
        {{ form.csrf_token }}

        <!-- 에러 처리 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}

        <div class="form-group">
            <label for="posting_password">게시글 비밀번호</label>
            <input type="password" class="form-control" name="posting_password" id="posting_password" value="{{ form.posting_password.data or '' }}">
        </div>
        <button class="btn btn-primary" type="submit">비밀번호 확인</button>
    </form>
</div>


{% endblock %}

flo/templates/board/board_write.html
<!-- 게시글 작성하기 -->

{% extends 'base.html' %}
{% block content %}
{% include "errors/form_errors.html" %}

<!-- 본문  -->
<div class="container">
    <h3 class="my-3 border-bottom py-2">게시글 작성</h3>
    <form  method="post" class="my-3" enctype="multipart/form-data">

        <!-- CSRF 토큰 처리 -->
        {{ form.csrf_token }}

        <!-- 에러 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}

        <!-- 게시글 작성 -->
        <div class="mb-3">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ form.title.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>

        <!-- 파일 업로드 -->
        <div class="form-group">
            <label for="fileupload">파일 업로드</label>
            <input type="file" class="form-control" name="fileupload" id="fileupload">
        </div>


        <!-- 비밀글 설정 -->
        <div class="mb-3">
            <label for="posting_password">게시글 비밀번호</label>
            <input type="password" class="form-control" name="posting_password" id="posting_password" value="{{ form.posting_password.data or '' }}">
        </div>

        <button class="btn btn-primary" type="submit" id="button-addon2">등록</button>

<!--        {% if not g.user %}-->
<!--            <button class="btn btn-primary" type="submit" id="button-addon2">등록</button>-->
<!--        {}% else %}-->
<!--            <button class="btn btn-primary" type="submit" id="button-addon2">등록</button>-->
<!--        {% endif %}-->
    </form>
</div>

{% endblock %}